services:
    _defaults:
        autoconfigure: true
        autowire: true

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    JBSupport\ContaoDeeplInstantTranslationBundle\:
        resource: '../../../src/*'
        exclude: '../../../src/{DependencyInjection,Entity,Resources}'

    JBSupport\ContaoDeeplInstantTranslationBundle\Classes\TranslationSettingsRegistry:
        public: true

    JBSupport\ContaoDeeplInstantTranslationBundle\EventListener\OutputFrontendTemplateListener:
        arguments:
            $registry: '@JBSupport\ContaoDeeplInstantTranslationBundle\Classes\TranslationSettingsRegistry'
        tags:
            - { name: contao.hook, hook: modifyFrontendPage, method: modifyTemplate }

    JBSupport\ContaoDeeplInstantTranslationBundle\EventListener\LanguageRedirectListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 150 }

